# Generated by Django 3.2.13 on 2023-09-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rankEdicao', models.CharField(max_length=10)),
                ('anoEdicao', models.CharField(max_length=30)),
                ('desempenho', models.CharField(max_length=20)),
                ('qualidadeDesempenho', models.CharField(choices=[('10', 'campeao'), ('5', 'vice'), ('4', 'semifinal'), ('3', 'quartas'), ('2', 'oitavas'), ('1', 'fase de grupos'), ('0', 'pré-liberta')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Razoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('razao', models.CharField(max_length=600)),
                ('importancia', models.CharField(max_length=50)),
                ('dataDeCadaAngustia', models.CharField(max_length=50)),
            ],
        ),
    ]
