# Generated by Django 3.2.13 on 2023-09-14 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdoRafael', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edicao',
            name='qualidadeDesempenho',
            field=models.CharField(choices=[('Campeão', '10'), ('Vice', '5'), ('Semifinalista', '4'), ('Quartas', '3'), ('Oitavas', '2'), ('Fase de Grupos', '1'), ('Pré-Libertadores', '0')], max_length=20),
        ),
    ]
